### ISSUE TITLE
Compatibility for pull requests

### ISSUE THREAD

**Issue by sidey79** [tool3/ncc#14]
I tried your action and got an errror:

`ncc failed! Cannot destructure property `email` of 'undefined' or 'null'.`

I think this is caused by the way the action tries to retrieve the property email (from a push).

So currently the action seems not to be compatible with pull request runs, only with push runs.

**Comment by tool3** [comment]
Yo @sidey79 !

Yup, totally a bug.

as mentioned in the other issue - I just made some changes and tested this - it should work now, please have a go and let me know if it works for you :)
