### ISSUE TITLE
zeit/ncc is no longer maintained

### ISSUE THREAD

**Issue by sidey79** [tool3/ncc#17]
I figured out that the commandline options i used before are not compatible:

Author message:

@zeit/ncc is no longer maintained. Please use @vercel/ncc instead.

Can you provide a version wich uses uptodate vercel/ncc.

**Comment by tool3** [comment]
just did :)

**Comment by sidey79** [comment]
Thanks you dir that quick fix.

I still have the Error with the Input params.

```
/usr/local/bin/npx @vercel/ncc build /home/runner/work/fhem-controls-actions/fhem-controls-actions/main.js -o  dist  --source-map  --license  licenses.txt
```

in my machine i used it very similar and it worked :
`
ncc build main.js -o dist --source-map --license licenses.txt
`

**Comment by sidey79** [comment]
Additional space charakters are both supported.

Now ist works

**Comment by tool3** [comment]
updated the code to trim the input args:
```javascript
const args = nccArgs.split(',').map(c => c.trim());
```

so now it should work with extra spaces in the input args as well.
