### ISSUE TITLE
Failure if the package hast no change

### ISSUE THREAD

**Issue by sidey79** [tool3/ncc#18]
If there is only a change in development used packages ncc does not create a changed file.

Git commit throws an error and the action itself ist failing at this point.

I think this should be covered or the push process completly removed from this action.

```
On branch dependabot/npm_and_yarn/jest-27.2.4
  Your branch is up to date with 'origin/dependabot/npm_and_yarn/jest-27.2.4'.
  
  nothing to commit, working tree clean
  Error: ncc failed! The process '/usr/bin/git' failed with exit code
```

**Comment by tool3** [comment]
Hey @sidey79 ! 

I added a try catch that handles empty commits - so it should work now.
